---
book_repo: pivotal-cf/docs-book-azure-analytics
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-azure-analytics
  directory: azure-log-analytics-nozzle
  subnav_template: azure-log-analytics-nozzle_subnav.erb
  product_info:
    use_local_header: true
    changelog_href: http://docs.pivotal.io/azure-log-analytics-nozzle/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Nozzle for VMware Tanzu for Microsoft Azure Log Analytics
    search_placeholder: Search Nozzle for VMware Tanzu for Microsoft Azure Log Analytics
    url_prefix: azure-log-analytics-nozzle/
    local_header_links: []
    skip_versioning: true
